GenericS3:
  - Disabled: false
    Endpoint: "YOURIP:9000"
    Key: "minioadmin"
    Secret: "minioadmin"

LocalStorage:
  # Whitelist of local directory paths which Funnel is allowed to access.
  AllowedDirs:
    - ./
    - /opt/funnel/funnel

AmazonS3:
  Disabled: true
  # The maximum number of times that a request will be retried for failures.
  MaxRetries: 10
  # AWS Access key ID
  Key: ""
  # AWS Secret Access Key
  Secret: ""

Database: mongodb

MongoDB:
  # Addresses for the seed servers.
  Addrs:
    - "mongo"
  # Database name used within MongoDB to store funnel data.
  Database: "funnel"
  Username: ""
  Password: ""